version: '3'

services:

  order_api:
    image: my-order-app
    working_dir: /usr/src/app
    command: order_app
    ports:
      - 0.0.0.0:8088:8088
    networks:
      - my-backend
    depends_on:
      - postgres_db

  payment_api:
      image: my-payment-app
      working_dir: /usr/src/app
      command: payment_app
      ports:
        - 0.0.0.0:8089:8089
      networks:
        - my-backend
      depends_on:
        - postgres_db

  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_system
    ports:
      - 0.0.0.0:5433:5432
    networks:
      - my-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  my-backend: